### ISSUE TITLE
Android SDK需要适配Android P，否则会直接crash

### ISSUE THREAD

**Issue by liangpengfei** [leancloud/java-sdk-all#13]
在Android P上，Google移除了apache库，不允许所有的app使用，需要升级项目代码使用HttpUrlConnection，否则项目会直接崩溃，支持Android P的手机马上就要批量上市了，现在Leancloud还没有完成适配，到时候所有使用Leancloud服务的app都会直接闪退！！
可以参考这个文章适配：https://segmentfault.com/a/1190000015276811
以下是报错：
> java.lang.NoClassDefFoundError: Failed resolution of: [Lorg/apache/http/Header;
        at com.avos.avoscloud.AsyncHttpResponseHandler.getHeaders(AsyncHttpResponseHandler.java:52)
        at com.avos.avoscloud.AsyncHttpResponseHandler.onResponse(AsyncHttpResponseHandler.java:42)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.http.Header" on path: DexPathList[[zip file "/data/app/com.neo.apollo.piratebay-Fh6jQ8nyLdpoPo-ca18r2w==/base.apk"],nativeLibraryDirectories=[/data/app/com.neo.apollo.piratebay-Fh6jQ8nyLdpoPo-ca18r2w==/lib/arm64, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:171)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.avos.avoscloud.AsyncHttpResponseHandler.getHeaders(AsyncHttpResponseHandler.java:52) 
        at com.avos.avoscloud.AsyncHttpResponseHandler.onResponse(AsyncHttpResponseHandler.java:42) 
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141) 
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764)

**Comment by jwfing** [comment]
这个问题在 老版本 sdk 中已经修复，本 sdk 中并不存在。
