### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/net/ssl/SNIHostName;

### ISSUE THREAD

**Issue by xfort** [leancloud/java-sdk-all#17]
使用LeanCloudChatKit-Android项目代码，leancloud sdk升级为5.0.2，
android  app  build.gradle配置
`
 compileSdkVersion 28
    buildToolsVersion "28.0.3"

    defaultConfig {
        applicationId "cn.leancloud.imkitapplication"
        minSdkVersion 19
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
    }
`

Android 项目 cn.leancloud:realtime-android:5.0.2 闪退
build.gradle 配置如下
`
dependencies {
    implementation 'com.android.support:support-v4:28.0.0'
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support:recyclerview-v7:28.0.0'

    implementation fileTree(dir:"libs", include:["*.jar"])
    implementation 'com.squareup.picasso:picasso:2.5.2'
    implementation 'de.greenrobot:eventbus:2.4.0'

    implementation 'io.reactivex.rxjava2:rxandroid:2.0.2'
    implementation("cn.leancloud:realtime-android:5.0.2"){
        exclude group: 'org.ligboy.retrofit2', module: 'converter-fastjson-android'
    }
    implementation 'com.alibaba:fastjson:1.1.68.android'
}

`
在Application中初始化
`
 LCChatKit.getInstance().setProfileProvider(CustomUserProvider.getInstance());
    AVOSCloud.setLogLevel(AVLogger.Level.DEBUG);
//    AVOSCloud.useAVCloudUS();
    LCChatKit.getInstance().init(getApplicationContext(), APP_ID, APP_KEY);

    PushService.setDefaultPushCallback(this, MainActivity.class);
    PushService.setAutoWakeUp(true);
    PushService.setDefaultChannelId(this, "default");

    AVInstallation.getCurrentInstallation().saveInBackground().subscribe(new Observer<AVObject>() {
      @Override
      public void onSubscribe(Disposable d) {
      }

      @Override
      public void onNext(AVObject avObject) {
        String installationId = AVInstallation.getCurrentInstallation().getInstallationId();
        System.out.println("---  " + installationId);
      }

      @Override
      public void onError(Throwable e) {
        // 保存失败，输出错误信息
        System.out.println("failed to save installation.");
      }

      @Override
      public void onComplete() {

      }
    });
`

启动闪退
`
12-27 18:46:10.336 2203-2203/? I/art: Late-enabling -Xcheck:jni
12-27 18:46:10.353 2203-2203/? D/TidaProvider: TidaProvider()
12-27 18:46:10.391 2203-2203/cn.leancloud.imkitapplication W/System: ClassLoader referenced unknown path: /data/app/cn.leancloud.imkitapplication-1/lib/arm64
12-27 18:46:10.395 2203-2203/cn.leancloud.imkitapplication I/MultiDex: VM with version 2.1.0 has multidex support
12-27 18:46:10.396 2203-2203/cn.leancloud.imkitapplication I/MultiDex: Installing application
12-27 18:46:10.396 2203-2203/cn.leancloud.imkitapplication I/MultiDex: VM has multidex support, MultiDex support library is disabled.
12-27 18:46:10.431 2203-2203/cn.leancloud.imkitapplication I/AVOSCloud: [LeanCloud] initialize mainThreadChecker and threadShuttle within AVCallback.
12-27 18:46:10.432 2203-2203/cn.leancloud.imkitapplication D/AVOSCloud: docDir=/data/user/0/cn.leancloud.imkitapplication/app_PaaS, fileDir=/data/user/0/cn.leancloud.imkitapplication/cache/avfile/, cmdDir=/data/user/0/cn.leancloud.imkitapplication/cache/CommandCache, statDir=/data/user/0/cn.leancloud.imkitapplication/cache/Analysis
12-27 18:46:10.464 2203-2203/cn.leancloud.imkitapplication D/AVIMMessageManager: failed to initialize message Fields
12-27 18:46:10.464 2203-2203/cn.leancloud.imkitapplication D/AVIMMessageManager: failed to initialize message Fields
12-27 18:46:10.465 2203-2203/cn.leancloud.imkitapplication D/AVIMMessageManager: failed to initialize message Fields
12-27 18:46:10.465 2203-2203/cn.leancloud.imkitapplication D/AVIMMessageManager: failed to initialize message Fields
12-27 18:46:10.465 2203-2203/cn.leancloud.imkitapplication D/AVIMMessageManager: failed to initialize message Fields
12-27 18:46:10.465 2203-2203/cn.leancloud.imkitapplication D/AVIMMessageManager: failed to initialize message Fields
12-27 18:46:10.466 2203-2203/cn.leancloud.imkitapplication D/AVIMMessageManager: failed to initialize message Fields
12-27 18:46:10.473 2203-2203/cn.leancloud.imkitapplication I/AndroidInitializer: [LeanCloud] initialize mainThreadChecker and threadShuttle within AVIMEventHandler.
12-27 18:46:10.473 2203-2203/cn.leancloud.imkitapplication I/AndroidInitializer: [LeanCloud] initialize mainThreadChecker and threadShuttle within AVLiveQueryEventHandler.
12-27 18:46:10.478 2203-2203/cn.leancloud.imkitapplication D/PushService: setDefaultPushCallback cls=cn.leancloud.chatkitapplication.MainActivity
12-27 18:46:10.481 2203-2245/cn.leancloud.imkitapplication D/PushService: Start service
12-27 18:46:10.482 2203-2203/cn.leancloud.imkitapplication D/PersistenceUtil: obtained read lock for file: /data/user/0/cn.leancloud.imkitapplication/files/installation
12-27 18:46:10.482 2203-2203/cn.leancloud.imkitapplication D/PersistenceUtil: release read lock for file: /data/user/0/cn.leancloud.imkitapplication/files/installation
12-27 18:46:10.493 2203-2203/cn.leancloud.imkitapplication D/AVObject: secondly, save object itself...
12-27 18:46:10.497 2203-2203/cn.leancloud.imkitapplication I/AVObject: saveObject param: {"deviceType":"android","timeZone":"Asia/Shanghai","installationId":"e34725271becb9950eedff98cca441f5"}
12-27 18:46:10.528 2203-2203/cn.leancloud.imkitapplication W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
12-27 18:46:10.541 2203-2203/cn.leancloud.imkitapplication D/AccessibilityManager: current package=cn.leancloud.imkitapplication, accessibility manager mIsFinalEnabled=false, mOptimizeEnabled=false, mIsUiAutomationEnabled=false, mIsInterestedPackage=false
12-27 18:46:10.553 2203-2203/cn.leancloud.imkitapplication I/art: Rejecting re-init on previously-failed class java.lang.Class<android.support.v4.view.ViewCompat$OnUnhandledKeyEventListenerWrapper>
12-27 18:46:10.553 2203-2203/cn.leancloud.imkitapplication I/art: Rejecting re-init on previously-failed class java.lang.Class<android.support.v4.view.ViewCompat$OnUnhandledKeyEventListenerWrapper>
12-27 18:46:10.607 2203-2255/cn.leancloud.imkitapplication D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
12-27 18:46:10.612 2203-2203/cn.leancloud.imkitapplication D/PushService: PushService#onCreate
12-27 18:46:10.613 2203-2257/cn.leancloud.imkitapplication D/AVConnectionManager: start connection...
12-27 18:46:10.614 2203-2257/cn.leancloud.imkitapplication D/AppRouter: fetchRTMServerFromRemote. router=https://dyrq8yfh.rtm.lncld.net, appId=dYRQ8YfHRiILshUnfFJu2eQM-gzGzoHsz
12-27 18:46:10.615 2203-2203/cn.leancloud.imkitapplication D/PushService: PushService#onStartCommand
12-27 18:46:10.617 2203-2203/cn.leancloud.imkitapplication D/PushService: networking is fine and try to start connection to leancloud.
12-27 18:46:10.617 2203-2203/cn.leancloud.imkitapplication D/AVConnectionManager: on starting connection, save callback...
12-27 18:46:10.658 2203-2255/cn.leancloud.imkitapplication I/Adreno: QUALCOMM build                   : 05151ca, I74772a33ad
    Build Date                       : 09/13/16
    OpenGL ES Shader Compiler Version: XE031.08.00.00
    Local Branch                     : 
    Remote Branch                    : refs/tags/AU_LINUX_ANDROID_LA.UM.5.3_RB1.06.00.01.211.047
    Remote Branch                    : NONE
    Reconstruct Branch               : NOTHING
12-27 18:46:10.662 2203-2203/cn.leancloud.imkitapplication D/AVConnectionManager: on starting connection, ignore.
12-27 18:46:10.662 2203-2203/cn.leancloud.imkitapplication D/PushService: Connection resumed with Wifi...
12-27 18:46:10.663 2203-2255/cn.leancloud.imkitapplication I/OpenGLRenderer: Initialized EGL, version 1.4
12-27 18:46:10.685 2203-2255/cn.leancloud.imkitapplication E/HAL: Dawei load: module=/system/lib64/hw/gralloc.msm8953.so
12-27 18:46:10.842 2203-2253/cn.leancloud.imkitapplication D/LoggingInterceptor: Request: curl -X POST 
     -H Accept: application/json 
     -H Content-Type: application/json 
     -H User-Agent: LeanCloud SDK v5.0.3 
     -H X-LC-Id: {your_app_id} 
     -H X-LC-Prod: 1 
     -H X-LC-Session: {your_session} 
     -H X-LC-Key: {your_app_key} 
    https://dyrq8yfh.api.lncld.net/1.1/installations?fetchWhenSave=false
12-27 18:46:10.843 2203-2253/cn.leancloud.imkitapplication D/LoggingInterceptor: Response: 201 
    server: nginx
    date: Thu, 27 Dec 2018 10:46:11 GMT
    content-type: application/json;charset=utf-8
    cache-control: no-cache,no-store
    pragma: no-cache
    strict-transport-security: max-age=31536000
     
    {"objectId":"WWf9zYCGAw1yTmjDO6kXtGmKnamcaTpV","createdAt":"2018-12-27T09:42:43.062Z","updatedAt":"2018-12-27T10:46:11.829Z"} 
12-27 18:46:10.850 2203-2203/cn.leancloud.imkitapplication D/PersistenceUtil: obtained writeLock for file: /data/user/0/cn.leancloud.imkitapplication/files/installation
12-27 18:46:10.850 2203-2203/cn.leancloud.imkitapplication D/PersistenceUtil: release writeLock for file: /data/user/0/cn.leancloud.imkitapplication/files/installation
12-27 18:46:10.850 2203-2203/cn.leancloud.imkitapplication I/System.out: ---  e34725271becb9950eedff98cca441f5
12-27 18:46:10.872 2203-2258/cn.leancloud.imkitapplication D/LoggingInterceptor: Request: curl -X GET 
     -H Accept: application/json 
     -H Content-Type: application/json 
     -H User-Agent: LeanCloud SDK v5.0.3 
     -H X-LC-Id: {your_app_id} 
     -H X-LC-Prod: 1 
     -H X-LC-Session: {your_session} 
     -H X-LC-Key: {your_app_key} 
    https://dyrq8yfh.rtm.lncld.net/v1/route?appId=dYRQ8YfHRiILshUnfFJu2eQM-gzGzoHsz&installationId=e34725271becb9950eedff98cca441f5&secure=1
12-27 18:46:10.873 2203-2258/cn.leancloud.imkitapplication D/LoggingInterceptor: Response: 200 
    server: nginx
    date: Thu, 27 Dec 2018 10:46:11 GMT
    content-type: application/json
    content-length: 169
    vary: Accept-Encoding
     
    {"groupId":"g0","server":"wss:\/\/rtm57.leancloud.cn\/","ttl":14400,"secondary":"wss:\/\/cn-n1-cell10.leancloud.cn\/","groupUrl":"https:\/\/router-g0-push.leancloud.cn"} 
12-27 18:46:10.898 2203-2257/cn.leancloud.imkitapplication D/AVConnectionManager: try to connect server: wss://rtm57.leancloud.cn/
    
    --------- beginning of crash
12-27 18:46:10.905 2203-2257/cn.leancloud.imkitapplication E/AndroidRuntime: FATAL EXCEPTION: Thread-14934
    Process: cn.leancloud.imkitapplication, PID: 2203
    java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/net/ssl/SNIHostName;
        at cn.leancloud.websocket.AVStandardWebSocketClient.setSocket(AVStandardWebSocketClient.java:91)
        at cn.leancloud.websocket.AVStandardWebSocketClient.<init>(AVStandardWebSocketClient.java:66)
        at cn.leancloud.session.AVConnectionManager.initWebSocketClient(AVConnectionManager.java:131)
        at cn.leancloud.session.AVConnectionManager.access$400(AVConnectionManager.java:37)
        at cn.leancloud.session.AVConnectionManager$2.onNext(AVConnectionManager.java:196)
        at cn.leancloud.session.AVConnectionManager$2.onNext(AVConnectionManager.java:188)
        at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:62)
        at io.reactivex.internal.operators.observable.ObservableScalarXMap$ScalarDisposable.run(ObservableScalarXMap.java:248)
        at io.reactivex.internal.operators.observable.ObservableJust.subscribeActual(ObservableJust.java:35)
        at io.reactivex.Observable.subscribe(Observable.java:12090)
        at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
        at io.reactivex.Observable.subscribe(Observable.java:12090)
        at cn.leancloud.session.AVConnectionManager.startConnectionInternal(AVConnectionManager.java:188)
        at cn.leancloud.session.AVConnectionManager.startConnection(AVConnectionManager.java:168)
        at cn.leancloud.push.PushService$1.run(PushService.java:100)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "javax.net.ssl.SNIHostName" on path: DexPathList[[zip file "/data/app/cn.leancloud.imkitapplication-1/base.apk"],nativeLibraryDirectories=[/data/app/cn.leancloud.imkitapplication-1/lib/arm64, /vendor/lib64, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at cn.leancloud.websocket.AVStandardWebSocketClient.setSocket(AVStandardWebSocketClient.java:91) 
        at cn.leancloud.websocket.AVStandardWebSocketClient.<init>(AVStandardWebSocketClient.java:66) 
        at cn.leancloud.session.AVConnectionManager.initWebSocketClient(AVConnectionManager.java:131) 
        at cn.leancloud.session.AVConnectionManager.access$400(AVConnectionManager.java:37) 
        at cn.leancloud.session.AVConnectionManager$2.onNext(AVConnectionManager.java:196) 
        at cn.leancloud.session.AVConnectionManager$2.onNext(AVConnectionManager.java:188) 
        at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:62) 
        at io.reactivex.internal.operators.observable.ObservableScalarXMap$ScalarDisposable.run(ObservableScalarXMap.java:248) 
        at io.reactivex.internal.operators.observable.ObservableJust.subscribeActual(ObservableJust.java:35) 
        at io.reactivex.Observable.subscribe(Observable.java:12090) 
        at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32) 
        at io.reactivex.Observable.subscribe(Observable.java:12090) 
        at cn.leancloud.session.AVConnectionManager.startConnectionInternal(AVConnectionManager.java:188) 
        at cn.leancloud.session.AVConnectionManager.startConnection(AVConnectionManager.java:168) 
        at cn.leancloud.push.PushService$1.run(PushService.java:100) 
        at java.lang.Thread.run(Thread.java:818) 
    	Suppressed: java.lang.ClassNotFoundException: javax.net.ssl.SNIHostName
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 17 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
12-27 18:46:10.924 2203-2257/? I/Process: Sending signal. PID: 2203 SIG: 9

`

**Comment by jwfing** [comment]
@xfort 我改了 LeanChat Android 版的 demo，运行是正常的，代码放在这里：https://github.com/leancloud/LeanCloudChatKit-Android/tree/v5.0.0
你可以参考一下。
