### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'void cn.leancloud.websocket.AVStandardWebSocketClient.send(cn.leancloud.command.CommandPacket)' on a null object reference

### ISSUE THREAD

**Issue by yangshizi** [leancloud/java-sdk-all#23]
调用 avLiveQuery.subscribeInBackground  方法时候
### java.lang.NullPointerException: Attempt to invoke virtual method 'void cn.leancloud.websocket.AVStandardWebSocketClient.send(cn.leancloud.command.CommandPacket)' on a null object reference
        at cn.leancloud.session.AVConnectionManager.sendPacket(AVConnectionManager.java:238)

### 完整

01-20 07:32:02.282 24593-24633/com.cooter.leancloud I/OpenGLRenderer: generate program for key:1800500044, use: 31 ms
01-20 07:32:05.959 24593-24666/com.cooter.leancloud D/LoggingInterceptor: Request: curl -X POST 
     -H Accept: application/json 
     -H Content-Type: application/json 
     -H User-Agent: LeanCloud SDK v5.0.8 
     -H X-LC-Id: {your_app_id} 
     -H X-LC-Prod: 1 
     -H X-LC-Session: {your_session} 
     -H X-LC-Key: {your_app_key} 
    https://allcawvw.api.lncld.net/1.1/LiveQuery/subscribe
01-20 07:32:05.962 24593-24666/com.cooter.leancloud D/LoggingInterceptor: Response: 200 
    server: nginx
    date: Sat, 19 Jan 2019 23:32:05 GMT
    content-type: application/json;charset=utf-8
    vary: Accept-Encoding
    cache-control: no-cache,no-store
    pragma: no-cache
    strict-transport-security: max-age=31536000
     
    {"id":"a3ae5e6b05183f16502d780dab3cbf72","query_id":"4db834d0b95f1e598b701c55ec5654a8"} 
01-20 07:32:06.009 24593-24593/com.cooter.leancloud D/DirectlyOperationTube: loginLiveQuery...
01-20 07:32:06.013 24593-24593/com.cooter.leancloud D/RequestCache: add request cache. client=leancloud_livequery_default_id, conv=null, request=-65535
01-20 07:32:06.058 24593-24593/com.cooter.leancloud W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'void cn.leancloud.websocket.AVStandardWebSocketClient.send(cn.leancloud.command.CommandPacket)' on a null object reference
01-20 07:32:06.058 24593-24593/com.cooter.leancloud W/System.err:     at cn.leancloud.session.AVConnectionManager.sendPacket(AVConnectionManager.java:238)
01-20 07:32:06.058 24593-24593/com.cooter.leancloud W/System.err:     at cn.leancloud.livequery.LiveQueryOperationDelegate.login(LiveQueryOperationDelegate.java:26)
01-20 07:32:06.058 24593-24593/com.cooter.leancloud W/System.err:     at cn.leancloud.im.DirectlyOperationTube.loginLiveQueryDirectly(DirectlyOperationTube.java:210)
01-20 07:32:06.058 24593-24593/com.cooter.leancloud W/System.err:     at cn.leancloud.im.DirectlyOperationTube.loginLiveQuery(DirectlyOperationTube.java:203)
01-20 07:32:06.058 24593-24593/com.cooter.leancloud W/System.err:     at cn.leancloud.livequery.AVLiveQuery.loginLiveQuery(AVLiveQuery.java:189)
01-20 07:32:06.058 24593-24593/com.cooter.leancloud W/System.err:     at cn.leancloud.livequery.AVLiveQuery.access$200(AVLiveQuery.java:26)
01-20 07:32:06.058 24593-24593/com.cooter.leancloud W/System.err:     at cn.leancloud.livequery.AVLiveQuery$1.onNext(AVLiveQuery.java:161)
01-20 07:32:06.058 24593-24593/com.cooter.leancloud W/System.err:     at cn.leancloud.livequery.AVLiveQuery$1.onNext(AVLiveQuery.java:150)
01-20 07:32:06.058 24593-24593/com.cooter.leancloud W/System.err:     at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
01-20 07:32:06.058 24593-24593/com.cooter.leancloud W/System.err:     at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
01-20 07:32:06.058 24593-24593/com.cooter.leancloud W/System.err:     at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:119)
01-20 07:32:06.058 24593-24593/com.cooter.leancloud W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
01-20 07:32:06.058 24593-24593/com.cooter.leancloud W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
01-20 07:32:06.058 24593-24593/com.cooter.leancloud W/System.err:     at android.os.Looper.loop(Looper.java:148)
01-20 07:32:06.058 24593-24593/com.cooter.leancloud W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5554)
01-20 07:32:06.058 24593-24593/com.cooter.leancloud W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
01-20 07:32:06.058 24593-24593/com.cooter.leancloud W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:935)
01-20 07:32:06.058 24593-24593/com.cooter.leancloud W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:726)
    
    --------- beginning of crash
01-20 07:32:06.059 24593-24593/com.cooter.leancloud E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.cooter.leancloud, PID: 24593
    java.lang.NullPointerException: Attempt to invoke virtual method 'void cn.leancloud.websocket.AVStandardWebSocketClient.send(cn.leancloud.command.CommandPacket)' on a null object reference
        at cn.leancloud.session.AVConnectionManager.sendPacket(AVConnectionManager.java:238)
        at cn.leancloud.livequery.LiveQueryOperationDelegate.login(LiveQueryOperationDelegate.java:26)
        at cn.leancloud.im.DirectlyOperationTube.loginLiveQueryDirectly(DirectlyOperationTube.java:210)
        at cn.leancloud.im.DirectlyOperationTube.loginLiveQuery(DirectlyOperationTube.java:203)
        at cn.leancloud.livequery.AVLiveQuery.loginLiveQuery(AVLiveQuery.java:189)
        at cn.leancloud.livequery.AVLiveQuery.access$200(AVLiveQuery.java:26)
        at cn.leancloud.livequery.AVLiveQuery$1.onNext(AVLiveQuery.java:161)
        at cn.leancloud.livequery.AVLiveQuery$1.onNext(AVLiveQuery.java:150)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
        at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:119)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5554)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:935)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:726)
    
    
    --------- beginning of system
01-20 07:32:06.073 24593-24593/com.cooter.leancloud I/Process: killProcess pid=24593
    java.lang.RuntimeException
        at android.os.Process.killProcess(Process.java:1142)
        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:100)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
        at io.reactivex.plugins.RxJavaPlugins.uncaught(RxJavaPlugins.java:429)
        at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:383)
        at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:121)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5554)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:935)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:726)
01-20 07:32:06.073 24593-24593/com.cooter.leancloud I/Process: Sending signal. PID: 24593 SIG: 9

**Comment by jwfing** [comment]
你 manifest 里面配置了 PushService 没有？

**Comment by yangshizi** [comment]
> 你 manifest 里面配置了 PushService 没有？
配置如下
<service
            android:name="cn.leancloud.push.PushService"
            android:exported="true" />

        <receiver android:name="cn.leancloud.push.AVBroadcastReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
                <action android:name="android.intent.action.USER_PRESENT" />
                <action android:name="android.net.conn.CONNECTIVITY_CHANGE" />
            </intent-filter>
        </receiver>

**Comment by yangshizi** [comment]
> 你 manifest 里面配置了 PushService 没有？


       <service
            android:name="cn.leancloud.push.PushService"
            android:exported="true" />

        <receiver android:name="cn.leancloud.push.AVBroadcastReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
                <action android:name="android.intent.action.USER_PRESENT" />
                <action android:name="android.net.conn.CONNECTIVITY_CHANGE" />
            </intent-filter>
        </receiver>

**Comment by jwfing** [comment]
好的，我今天测试一下。

**Comment by jwfing** [comment]
确实连接没有初始化，我们会尽快修复，你可以现在 Application#onCreate 函数中增加如下的代码来手动初始化一下：
```
    new Thread(new Runnable() {
      @Override
      public void run() {
        AVConnectionManager.getInstance().startConnection(new AVCallback() {
          @Override
          protected void internalDone0(Object o, AVException avException) {
          }
        });
      }
    }).start();
```

**Comment by jwfing** [comment]
@yangshizi 你们是只使用 LiveQuery，不使用 推送 或者 即时通讯 吗？
