### ISSUE TITLE
5.0.10 crash

### ISSUE THREAD

**Issue by CrawlerChaos** [leancloud/java-sdk-all#34]
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
        at java.net.URI$Parser.parse(URI.java:3050)
        at java.net.URI.<init>(URI.java:590)
        at java.net.URI.create(URI.java:852)
        at cn.leancloud.l.b.b(AVConnectionManager.java:134)
        at cn.leancloud.l.b.a(AVConnectionManager.java:37)
        at cn.leancloud.l.b$2.a(AVConnectionManager.java:196)
        at cn.leancloud.l.b$2.onNext(AVConnectionManager.java:188)
        at io.a.e.e.b.f$a.onNext(ObservableMap.java:62)
        at io.a.e.e.b.i$a.run(ObservableScalarXMap.java:248)
        at io.a.e.e.b.e.b(ObservableJust.java:35)
        at io.a.e.a(Observable.java:12090)
        at io.a.e.e.b.f.b(ObservableMap.java:32)
        at io.a.e.a(Observable.java:12090)
        at cn.leancloud.l.b.h(AVConnectionManager.java:188)
        at cn.leancloud.l.b.b(AVConnectionManager.java:168)
        at cn.leancloud.push.PushService$1.run(PushService.java:100)
        at java.lang.Thread.run(Thread.java:761)

**Comment by weakish** [comment]
具体是什么代码触发了 crash？5.0.11 下能复现吗？

**Comment by CrawlerChaos** [comment]
> 具体是什么代码触发了 crash？5.0.11 下能复现吗？

我升级试试

**Comment by lynnzc** [comment]
![image](https://user-images.githubusercontent.com/6257996/53543333-5379cf80-3b5d-11e9-8b39-dc29969d5977.png)

**Comment by lynnzc** [comment]
经常出现这个报错 @weakish

**Comment by jwfing** [comment]
@lynnzc 你能把 android app 从启动开始的 debug 日志都贴出来吗？出现这个错误是比较诡异的，怀疑与 applicaiton 初始化不对有关系，我需要直接看客户端与服务端交互的 debug 日志。

**Comment by jwfing** [comment]
你好，realtime-android 5.0.12 版本已经发布，修复了这个问题。
