### ISSUE TITLE
 PushService.subscribe()方法添加多条订阅的时候崩溃UnsupportedOperationException

### ISSUE THREAD

**Issue by AndroidCrow** [leancloud/java-sdk-all#39]
Caused by: java.lang.UnsupportedOperationException
        at java.util.AbstractList.add(AbstractList.java:148)
        at java.util.AbstractList.add(AbstractList.java:108)
        at java.util.AbstractCollection.addAll(AbstractCollection.java:342)
        at cn.leancloud.ops.AddOperation.apply(AddOperation.java:24)
        at cn.leancloud.AVObject.addNewOperation(AVObject.java:399)
        at cn.leancloud.AVObject.addUnique(AVObject.java:333)
        at cn.leancloud.push.PushService.subscribe(PushService.java:264)
        at com.fhedu.student.manage.PushManage$1.onNext(PushManage.java:45)
        at com.fhedu.student.manage.PushManage$1.onNext(PushManage.java:26)
        at io.reactivex.internal.operators.flowable.FlowableFromObservable$SubscriberObserver.onNext(FlowableFromObservable.java:54)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)

**Comment by jwfing** [comment]
你好，realtime-android 5.0.12 版本已经发布，修复了这个问题。
