### ISSUE TITLE
AVInstallation.getCurrentInstallation().remove 的时候崩溃  

### ISSUE THREAD

**Issue by AndroidCrow** [leancloud/java-sdk-all#40]
addNewOperation方法中    Object newValue = op.apply(oldValue);（这句话源码里面直接返回的是空)下面put直接就崩
this.serverData.put(op.getField(), newValue);

 Caused by: java.lang.NullPointerException
        at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:990)
        at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:985)
        at cn.leancloud.AVObject.addNewOperation(AVObject.java:400)
        at cn.leancloud.AVObject.remove(AVObject.java:350)
        at com.fhedu.student.manage.PushManage.subscribeClass(PushManage.java:26)

**Comment by jwfing** [comment]
你好，realtime-android 5.0.12 版本已经发布，修复了这个问题。
